import { EvidencePackage, Challenge, ClassificationRecord } from "./types";

export const mockPackages: EvidencePackage[] = [
  {
    id: "pkg-001",
    depositor: "0x7f3a...4e2c",
    title: "DAO Treasury Misallocation — Q3 2024",
    claim: "The DAO treasury transferred 450,000 USDC to an undisclosed wallet on September 14, 2024, bypassing the required governance vote threshold.",
    evidenceType: "transaction",
    eventDate: "2024-09-14",
    captureDate: "2024-09-15",
    submittedAt: "2024-09-16T10:23:00Z",
    primarySources: ["https://etherscan.io/tx/0xabc123", "https://snapshot.org/#/dao/proposal/xyz"],
    supportingSources: ["https://forum.dao.org/thread/treasury-movement-concerns"],
    fileHashes: ["sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"],
    archiveLinks: ["https://web.archive.org/web/20240915/https://etherscan.io/tx/0xabc123"],
    contextNote: "The transaction occurred 3 hours before the governance vote closed. Multi-sig threshold was 4/7 but only 3 signers approved.",
    knownLimitations: "On-chain data alone does not prove intent. The recipient address has not been publicly identified.",
    knownDisputes: "Core team claims this was an emergency withdrawal under Section 12 of the DAO constitution.",
    whyMatters: "If confirmed, this would represent a breach of DAO governance and a potential precedent for treasury security.",
    sensitivityLevel: "public",
    requestedClassification: "authentic",
    historicalSignificanceNote: "First documented governance bypass in this DAO's history.",
    status: "classified",
    currentClassification: "context_required",
    confidence: "medium",
    manipulationRisk: "low",
    significance: "high",
    sourceAlignment: "partial",
    preservationPriority: "elevated",
    shortReason: "Transaction data is verifiable on-chain but the emergency clause invocation requires review of DAO constitution text.",
    challengeCount: 2,
    classificationCount: 1,
  },
  {
    id: "pkg-002",
    depositor: "0x2b8f...9a1d",
    title: "Protocol Founder Public Commitment — Token Lockup",
    claim: "Founder publicly committed to a 4-year token lockup with no early unlock provisions in a recorded AMA session on March 3, 2023.",
    evidenceType: "video",
    eventDate: "2023-03-03",
    captureDate: "2023-03-04",
    submittedAt: "2024-01-12T14:00:00Z",
    primarySources: ["https://youtube.com/watch?v=example123", "https://twitter.com/founder/status/12345"],
    supportingSources: ["https://medium.com/@founder/commitment-post"],
    fileHashes: ["sha256:abc123def456", "sha256:789xyz012abc"],
    archiveLinks: ["https://web.archive.org/web/20230304/https://twitter.com/founder/status/12345"],
    contextNote: "The AMA was attended by approximately 12,000 live viewers. The statement was made at timestamp 1:24:33.",
    sensitivityLevel: "public",
    requestedClassification: "authentic",
    status: "classified",
    currentClassification: "authentic",
    confidence: "high",
    manipulationRisk: "low",
    significance: "high",
    sourceAlignment: "strong",
    preservationPriority: "elevated",
    shortReason: "Video source, archive link, and social media post all align. Statement is unambiguous and timestamped.",
    challengeCount: 0,
    classificationCount: 1,
  },
  {
    id: "pkg-003",
    depositor: "0x9c5e...3f7b",
    title: "Whistleblower Report — Internal Safety Incident",
    claim: "An internal safety incident on November 8, 2024 was deliberately concealed from public disclosure required under applicable regulations.",
    evidenceType: "document",
    eventDate: "2024-11-08",
    captureDate: "2024-11-20",
    submittedAt: "2024-11-22T08:45:00Z",
    primarySources: ["ipfs://QmXyz789whistleblower"],
    supportingSources: [],
    fileHashes: ["sha256:wbr_doc_hash_001", "sha256:wbr_doc_hash_002"],
    archiveLinks: [],
    contextNote: "Documents were provided by an internal source. Author identity is protected.",
    knownLimitations: "Source documents cannot be independently verified without access to internal systems.",
    sensitivityLevel: "sensitive",
    requestedClassification: "historically_significant",
    status: "challenged",
    currentClassification: "incomplete",
    confidence: "low",
    manipulationRisk: "unknown",
    significance: "high",
    sourceAlignment: "unverifiable",
    preservationPriority: "restricted_review",
    shortReason: "Primary source is a private IPFS document with no corroborating public evidence accessible to validators.",
    challengeCount: 1,
    classificationCount: 1,
  },
  {
    id: "pkg-004",
    depositor: "0x4d2a...8c6e",
    title: "Community Governance Proposal — Deleted Forum Post",
    claim: "A governance proposal that received majority community support was silently deleted from the official forum before the voting deadline.",
    evidenceType: "screenshot",
    eventDate: "2024-07-19",
    captureDate: "2024-07-19",
    submittedAt: "2024-07-20T16:30:00Z",
    primarySources: ["https://forum.protocol.io/t/proposal-12345"],
    supportingSources: ["https://twitter.com/community_watch/status/67890"],
    fileHashes: ["sha256:screenshot_hash_forum"],
    archiveLinks: ["https://web.archive.org/web/20240719/https://forum.protocol.io/t/proposal-12345"],
    contextNote: "The archive link captures the forum post at 14:32 UTC. The post was removed by 17:00 UTC.",
    sensitivityLevel: "public",
    requestedClassification: "authentic",
    status: "classified",
    currentClassification: "historically_significant",
    confidence: "medium",
    manipulationRisk: "low",
    significance: "historic",
    sourceAlignment: "strong",
    preservationPriority: "urgent",
    shortReason: "Archive link corroborates the screenshot. This record documents a censorship event with significant governance implications.",
    challengeCount: 0,
    classificationCount: 1,
  },
  {
    id: "pkg-005",
    depositor: "0x1f7b...5d3a",
    title: "Alleged Market Manipulation — Coordinated Wash Trading",
    claim: "A cluster of 14 wallets engaged in coordinated wash trading to artificially inflate 30-day volume metrics on a DEX between April 1–15, 2024.",
    evidenceType: "transaction",
    eventDate: "2024-04-01",
    captureDate: "2024-04-16",
    submittedAt: "2024-04-18T11:15:00Z",
    primarySources: ["https://dune.com/dashboard/wash-trading-analysis"],
    supportingSources: ["https://etherscan.io/address/0xwallet1", "https://etherscan.io/address/0xwallet2"],
    fileHashes: [],
    archiveLinks: ["https://web.archive.org/web/20240416/https://dune.com/dashboard/wash-trading-analysis"],
    contextNote: "Analysis was conducted by an independent blockchain analytics researcher. Methodology is documented in the Dune dashboard.",
    knownLimitations: "Wash trading requires proving coordination. On-chain patterns are consistent but not conclusive proof of intent.",
    sensitivityLevel: "public",
    requestedClassification: "authentic",
    status: "challenged",
    currentClassification: "disputed",
    confidence: "medium",
    manipulationRisk: "unknown",
    significance: "medium",
    sourceAlignment: "partial",
    preservationPriority: "standard",
    shortReason: "On-chain patterns support the claim but a credible challenge questions the methodology and wallet attribution.",
    challengeCount: 3,
    classificationCount: 2,
  },
  {
    id: "pkg-006",
    depositor: "0x8e4c...2b9f",
    title: "Historical Smart Contract Deployment — Genesis Block",
    claim: "This package preserves the original deployment transaction and source code for one of the earliest DeFi protocols, deployed in 2019.",
    evidenceType: "archive",
    eventDate: "2019-11-04",
    captureDate: "2024-06-01",
    submittedAt: "2024-06-05T09:00:00Z",
    primarySources: ["https://etherscan.io/tx/0xgenesis2019"],
    supportingSources: ["https://github.com/original-protocol/contracts"],
    fileHashes: ["sha256:genesis_contract_hash", "sha256:source_code_hash"],
    archiveLinks: ["https://web.archive.org/web/20191104/https://etherscan.io/tx/0xgenesis2019"],
    contextNote: "Preserving this record because the original GitHub repository has been archived and may be deleted.",
    sensitivityLevel: "public",
    requestedClassification: "historically_significant",
    status: "classified",
    currentClassification: "historically_significant",
    confidence: "high",
    manipulationRisk: "low",
    significance: "historic",
    sourceAlignment: "strong",
    preservationPriority: "urgent",
    shortReason: "On-chain deployment record is immutable and verifiable. Historical significance is unambiguous.",
    challengeCount: 0,
    classificationCount: 1,
  },
  {
    id: "pkg-007",
    depositor: "0x3c9d...7e1a",
    title: "Manipulated Price Feed Screenshot",
    claim: "The price oracle showed $0.000001 for 3 seconds during a flash loan attack, allowing an exploiter to drain 2M USDC from the protocol.",
    evidenceType: "screenshot",
    eventDate: "2024-08-22",
    captureDate: "2024-08-22",
    submittedAt: "2024-08-23T07:00:00Z",
    primarySources: ["https://example.com/oracle-screenshot"],
    supportingSources: [],
    fileHashes: [],
    archiveLinks: [],
    contextNote: "Single screenshot with no timestamp metadata or source URL visible.",
    sensitivityLevel: "public",
    requestedClassification: "authentic",
    status: "classified",
    currentClassification: "weak",
    confidence: "low",
    manipulationRisk: "medium",
    significance: "medium",
    sourceAlignment: "weak",
    preservationPriority: "standard",
    shortReason: "Screenshot lacks metadata, timestamp, or corroborating on-chain evidence for the claimed price anomaly.",
    challengeCount: 0,
    classificationCount: 1,
  },
  {
    id: "pkg-008",
    depositor: "0x6a1e...4c8b",
    title: "Pending Classification — Protocol Incident Report",
    claim: "A critical vulnerability was discovered and patched without public disclosure. This package preserves internal communications about the decision.",
    evidenceType: "document",
    eventDate: "2024-12-01",
    captureDate: "2024-12-10",
    submittedAt: "2024-12-11T15:00:00Z",
    primarySources: ["ipfs://QmPending001"],
    supportingSources: [],
    fileHashes: ["sha256:pending_hash_001"],
    archiveLinks: [],
    contextNote: "Awaiting validator review.",
    sensitivityLevel: "limited",
    requestedClassification: "context_required",
    status: "pending",
    currentClassification: "",
    confidence: "",
    manipulationRisk: "",
    significance: "",
    sourceAlignment: "",
    preservationPriority: "",
    shortReason: "",
    challengeCount: 0,
    classificationCount: 0,
  },
];

export const mockChallenges: Challenge[] = [
  {
    id: "ch-001",
    packageId: "pkg-001",
    challenger: "0x5b3f...8d2e",
    challengeType: "missing_context",
    counterEvidence: ["https://dao.constitution.org/section-12"],
    archiveLinks: [],
    hashes: [],
    challengeNote: "Section 12 of the DAO Constitution explicitly grants the multisig emergency withdrawal powers without requiring a governance vote when the treasury is at risk. The depositor has omitted this context.",
    status: "open",
    submittedAt: "2024-09-18T12:00:00Z",
  },
  {
    id: "ch-002",
    packageId: "pkg-001",
    challenger: "0x7a2c...1f5d",
    challengeType: "wrong_classification",
    counterEvidence: ["https://snapshot.org/#/dao/proposal/emergency-vote"],
    archiveLinks: [],
    hashes: [],
    challengeNote: "An emergency governance vote was held retroactively and ratified the action by 78% majority. The classification should reflect this resolution.",
    status: "open",
    submittedAt: "2024-09-20T09:30:00Z",
  },
  {
    id: "ch-003",
    packageId: "pkg-003",
    challenger: "0x9e4b...6c3a",
    challengeType: "false_claim",
    counterEvidence: [],
    archiveLinks: [],
    hashes: [],
    challengeNote: "The regulatory disclosure requirement cited does not apply to decentralized protocols. The claim misrepresents the legal framework.",
    status: "open",
    submittedAt: "2024-11-25T14:00:00Z",
  },
  {
    id: "ch-004",
    packageId: "pkg-005",
    challenger: "0x2d7a...9b4c",
    challengeType: "manipulation_claim",
    counterEvidence: ["https://alternative-analysis.org/dex-volume-report"],
    archiveLinks: [],
    hashes: [],
    challengeNote: "The Dune dashboard methodology incorrectly attributes multiple independent arbitrage bots to a coordinated cluster. The wallet graph analysis has a known flaw.",
    status: "open",
    submittedAt: "2024-04-20T16:00:00Z",
  },
  {
    id: "ch-005",
    packageId: "pkg-005",
    challenger: "0x4f1e...7a2d",
    challengeType: "stronger_evidence_available",
    counterEvidence: ["https://chainalysis.com/report/dex-wash-trading-2024"],
    archiveLinks: [],
    hashes: [],
    challengeNote: "A more rigorous on-chain analysis with MEV data included actually supports the original claim but with a different set of wallets.",
    status: "open",
    submittedAt: "2024-04-22T11:00:00Z",
  },
  {
    id: "ch-006",
    packageId: "pkg-005",
    challenger: "0x8c3b...5e1f",
    challengeType: "missing_context",
    counterEvidence: [],
    archiveLinks: [],
    hashes: [],
    challengeNote: "The DEX uses a volume incentive program that naturally creates repetitive transaction patterns that superficially resemble wash trading.",
    status: "resolved",
    submittedAt: "2024-04-24T08:00:00Z",
  },
];

export const mockClassificationHistory: ClassificationRecord[] = [
  {
    id: "cr-001",
    packageId: "pkg-001",
    classification: "context_required",
    confidence: "medium",
    manipulationRisk: "low",
    significance: "high",
    sourceAlignment: "partial",
    preservationPriority: "elevated",
    shortReason: "Transaction data is verifiable on-chain but the emergency clause invocation requires review of DAO constitution text.",
    reasonType: "initial",
    timestamp: "2024-09-17T08:00:00Z",
  },
  {
    id: "cr-002",
    packageId: "pkg-002",
    classification: "authentic",
    confidence: "high",
    manipulationRisk: "low",
    significance: "high",
    sourceAlignment: "strong",
    preservationPriority: "elevated",
    shortReason: "Video source, archive link, and social media post all align. Statement is unambiguous and timestamped.",
    reasonType: "initial",
    timestamp: "2024-01-13T10:00:00Z",
  },
  {
    id: "cr-003",
    packageId: "pkg-005",
    classification: "context_required",
    confidence: "medium",
    manipulationRisk: "low",
    significance: "medium",
    sourceAlignment: "partial",
    preservationPriority: "standard",
    shortReason: "Initial on-chain analysis patterns support the claim but methodology requires further scrutiny.",
    reasonType: "initial",
    timestamp: "2024-04-19T10:00:00Z",
  },
  {
    id: "cr-004",
    packageId: "pkg-005",
    classification: "disputed",
    confidence: "medium",
    manipulationRisk: "unknown",
    significance: "medium",
    sourceAlignment: "contradictory",
    preservationPriority: "standard",
    shortReason: "On-chain patterns support the claim but a credible challenge questions the methodology and wallet attribution.",
    reasonType: "reclassification",
    timestamp: "2024-04-25T14:00:00Z",
  },
];
